### ISSUE TITLE
Approval Timeline

### ISSUE THREAD

**Issue by manoranjanp** [gdg-wisdom/wisdom-2015#23] opened 2015-10-16 13:40 UTC
Hello,

How much time they take for processing the application status once filling up the form. It has been more then 2 Weeks since I applied to start a new GDG Chapter.

Thanks

**Comment by friedger** [comment] 2015-10-17 14:59
It looks like nobody here knows the answer. Could you send an email to the
Google group gdg-leads-admin?

**Comment by nitya** [comment] 2015-10-17 15:06
Was away at a conference so didn't reply earlier.

The best person to ask is your regional mentor. Where is your chapter? I
can ask folks I know about status as well if it helps

Best
Nitya

**Comment by friedger** [comment] 2015-10-17 15:10
The answer for the general case should be in
https://gdg-wisdom.gitbooks.io/gdg-wisdom-2015/content/what_is_a_gdg/incubating.html

If you filled out the form you might not now your regional mentor yet..

**Comment by nitya** [comment] 2015-10-17 16:33
That's a great point!! We should update the Mentoring page (
https://gdg-wisdom.gitbooks.io/gdg-wisdom-2015/content/what_is_a_gdg/mentoring.html)
with a list of the mentors and their contact information.

I know we have a community for the NA Mentors and can update that soon. Can
find out about other mentors as well,

cheers
Nitya

On Sat, Oct 17, 2015 at 10:10 AM, Friedger Müffke <notifications@github.com>
wrote:

> The answer for the general case should be in
>
> https://gdg-wisdom.gitbooks.io/gdg-wisdom-2015/content/what_is_a_gdg/incubating.html
>
> If you filled out the form you might not now your regional mentor yet..
> On 17 Oct 2015 5:06 pm, "Nitya Narasimhan" <notifications@github.com>
> wrote:
>
> > Was away at a conference so didn't reply earlier.
> >
> > The best person to ask is your regional mentor. Where is your chapter? I
> > can ask folks I know about status as well if it helps
> >
> > Best
> > Nitya
> > On Oct 17, 2015 9:59 AM, "Friedger Müffke" <notifications@github.com>
> > wrote:
> >
> > > It looks like nobody here knows the answer. Could you send an email to
> > the
> > > Google group gdg-leads-admin?
> > > On 16 Oct 2015 3:40 pm, "Manoranjan Padhy" <notifications@github.com>
> > > wrote:
> > >
> > > > Hello,
> > > >
> > > > How much time they take for processing the application status once
> > > filling
> > > > up the form. It has been more then 2 Weeks since I applied to start a
> > new
> > > > GDG Chapter.
> > > >
> > > > Thanks
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/gdg-wisdom/wisdom-2015/issues/23>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/gdg-wisdom/wisdom-2015/issues/23#issuecomment-148921788
> > >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/gdg-wisdom/wisdom-2015/issues/23#issuecomment-148922087
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdg-wisdom/wisdom-2015/issues/23#issuecomment-148922296>
> .
>



-- 
*Nitya Narasimhan, PhD*
*VP Engineering @Cheerity  <http://bit.ly/cheerity-co>*
*Organizer, Google Developer Groups @NYC @HV*
*Organizer, Meteor Hudson Valley*

Hudson Valley, NY

*Profile: linkedin <http://bit.ly/nitya-in> *
<http://bit.ly/nitya-blog>**twitter
<http://bit.ly/nitya-twitter> * google <http://bit.ly/nitya-google> * **blog
<http://bit.ly/nitya-blog> * github <http://bit.ly/nitya-github>*
*Meetup*: *GDG Hudson Valley
<http://www.meetup.com/gdg-hudson-valley/>, GDG New York
<http://www.meetup.com/NYC-GDG/>, Meteor Hudson Valley
<http://www.meetup.com/Meteor-Hudson-Valley/>*

**Comment by manoranjanp** [comment] 2015-10-18 05:06
Hello,

I have already sent an email to admin [at] gdgroups [dot] org but didn't get a response from him. Also, the acknowledgement mail which I received after filling up the form, I tried replying to it as the time period specified my the mail to resolve the issue was already over but again no luck there too.

I don't know the regional mentor yet as specified by @friedger . The chapter which I wish to start is located in Gujarat, India @nitya . Any help you guys can do? Thanks.

**Comment by kenju254** [comment] 2015-10-18 19:53
Hi @manoranjanp , GDG applications are handled by regional leads from the Google DevRel Team.. At least for SSA (Sub Saharan Africa) those are the guys who process the application. I would recommend that you try contact your regional lead for India, If I am not wrong, the person's name is Uttam Tripathi . @nitya I am not sure if the mentor program is in India. I am sure of Sub-Saharan Africa and in America region.

**Comment by friedger** [comment] 2015-10-20 07:20
@manoranjanp You should get an email by Sunil Rao N A  soon.

**Comment by friedger** [comment] 2015-10-20 07:24
The approval time is 2 weeks. Fixed by https://github.com/gdg-wisdom/wisdom-2015/commit/fd734411fd7bc39e88f8e780e42298536f6bb661

**Closed by friedger** 2015-10-20 07:24 UTC

**Comment by manoranjanp** [comment] 2015-10-20 07:28
@friedger It has been 3 Weeks already, I haven't got any team from Developers Group Team or Sunil Rao.

**Comment by manoranjanp** [comment] 2015-10-20 07:29
*Email

**Comment by friedger** [comment] 2015-10-20 07:32
@manoranjanp Sunil confirmed yesterday that he will get in contact with you. I was told that Google's workflow is setup that you usually should get a reply within 2 weeks. Your application seems to have slipped through their system somewhere which is unfortunate and I would have expected better from such a company :-)

However, for no the gdg wisdom project can't do much more, hence, I closed the ticket.

**Comment by manoranjanp** [comment] 2015-10-20 10:57
@friedger thanks! Even I didn't expect anything like from a Big Company. -:)
